/* eslint-disable no-undef */

exports.MESSAGES = {
  INVALID_EMAIL: 'Please provide a valid email address.',
  INVALID_CREDENTIALS: 'Please provide a valid Credentials',
  INVALID_ID: 'Please provide a valid id',
  INVALID_OTP: 'Please provide a valid otp',
  INVALID_DATA: 'Please provide a valid Data',
  NO_DATA_FOUND: 'No Data Found',
  INVALID_SUBDOMAIN_NAME: 'Please provide a valid subdomain name',
  FAILED_TO_CREATE: 'Failed to create',
  FAILED_TO_SEND_EMAIL: 'Unfortunately, the email could not be sent',
  FAILED_TO_UPDATE: 'Failed to update',
  FAILED_TO_UPLOAD: 'Failed to upload file',
  FAILED_TO_DELETE: 'Failed to delete',
  RECORD_ALREADY_EXIST: 'Record already exist',
  QUIZE_ALREADY_EXIST: 'Quize have already added in quizedate',
  RECORD_NOT_FOUND: 'Record not found',
  USER_LOGIN_SUCCESSFULLY: 'User logged in successfully',
  ADMIN_LOGIN_SUCCESSFULLY: 'Admin logged in successfully',
  ADMIN_DELETE_SUCCESSFULLY: 'Admin record delete successfully',
  USERS_DELETE_SUCCESSFULLY: 'User record delete successfully',
  SOMETHING_WENT_WRONG: 'Something went wrong please try again',
  NOT_ALLOW_TO_CREATE: 'Not allow to create record',
  NOT_ALLOW_TO_UPDATE: 'Not allow to update record',
  NOT_ALLOW_TO_DELETE: 'Not allow to delete record',
  REPORT_NOT_ALLOW_GENERATE: 'Report not being able to be generated - Product result not found.',
  LEDGER_REPORT_NOT_ALLOW_GENERATE: 'Report not being able to be generated - general ledger result not found.',
  REGISTRATION_SUCCESS: 'Registration successful.',
  REGISTRATION_DUPLICATE_EMAIL: 'Email already in use.',
  REGISTRATION_ADMIN_EMAIL: 'This Email already use in Admin account try with diffrent email',
  REGISTRATION_USER_EMAIL: 'This Email already use in User account try with diffrent email',
  REGISTRATION_ERROR: 'Error occurred during registration.',
  EMAIL_VERIFICATION_SENT: 'Email verification link sent successfully in email.',
  PASSWORD_RESET_SENT: 'Password reset otp sent successfully in email.',
  VERIFICATION_LINK_EXPIRED: 'Verification link has expired. Please sign up again.',
  EMAIL_VERIFIED: 'Email verification successful. Your account is now verified.',
  FIRST_EMAIL_VERIFIED: 'Before login you need to verify your email. Please check your email',
  PASSWORD_RESET_VERIFIED_EMAIL: 'Before password chnage you need to verify your email. Please check your email',
  PASSWORD_RESET_SUCCESS: 'Password reset successful. Your password has been updated.',
  USERNAME_UPDATE_SUCCESS: 'Username successfully updated.',
  PASSWORD_UPDATE_SUCCESS: 'User password successfully updated.',
  USERIMAGE_UPDATE_SUCCESS: 'User profile picture successfully updated.',
  OLD_PASSWORD_WRONG: 'Old password is incorrect. Please try again.',
  FAILED_TO_AUTHENTICATE: 'Failed to authenticate token.',
  UNAUTHORIZED_USER: 'Unauthorized user.',
  TOKEN_AUTHORIZED_SUCCESS: 'Token verification successful.',
  TOKEN_REQUIRED: 'No token provided.',
  TOKEN: "User Unauthenticated",
  FILE_RECEIVE_SUCCESS: 'We have received your file successfully. After verifying the file, we will promptly establish a connection with you.',
  CREDIT_ALREADY_ADDED: 'Credit Already added in your account',
  REQ_USER_ID: "Please provide a userid",
  REQ_PRIFIX: "Please provide a prifix",
  CREDIT_REQ: "You need to buy credit to see prefix details",
  FILE_REQ: "File not found",
  FILE_INCORRECT: "Incorrect File uploaded",
  FILE_UPLOAD_SUCCESS: "File uploaded successfully",
  INV_FILE_TYPE: "Invalid file selected used CSV",
  BLOCK_USER: 'Your account blocked by admin',
};

exports.SMTPConfig = {
  EMAIL: 'admin@fanatiqtrivia.com',
  PASSWORD: 'lezt osiz jihc baws',
  HOST: 'smtp.gmail.com',
  PORT: 587,
  FROM_EMAIL: 'admin@fanatiqtrivia.com  ',
};

exports.SMTPSupportConfig = {
  EMAIL: 'support@fanatiqtrivia.com',
  PASSWORD: 'txwg sjsq lzpd kxyd',
  HOST: 'smtp.gmail.com',
  PORT: 587,
  FROM_EMAIL: 'support@fanatiqtrivia.com',
}

exports.REPORT_PATH = {
  EXCEL_REPORT: '/reports/excel/',
};